#!/usr/bin/env Rscript
args = commandArgs(trailingOnly=TRUE)

library(maptools)
library(dplyr)
library(ggplot2)
library(raster)
library(xts)

df <- readRDS(paste0('ncdcOisst2Agg_LonPM180_',args[1],'-01-01_',args[1],'-12-31.Rda'))
df$lat <- round(df$lat,2); df$lon <- round(df$lon,2)

df.arr <- split(df, paste0(df$lon,"_",df$lat))
arr.xts <- lapply(df.arr, function(x) xts(x$var, x$t))
xc <- do.call(merge, arr.xts)

weekly.max <- apply.weekly(xc,apply,2,max)
weekly.min <- apply.weekly(xc,apply,2,min)
weekly.range <- data.frame(matrix(as.numeric(weekly.max)-as.numeric(weekly.min), ncol = ncol(weekly.max)), row.names = index(weekly.max))
annual.weekly.range <- data.frame(apply.yearly(weekly.range,mean))
overall.weekly.range <- apply(weekly.range,2,mean)
monthly.max <- apply.monthly(xc,apply,2,max)
monthly.min <- apply.monthly(xc,apply,2,min)
monthly.mean <- apply.monthly(xc,mean)
monthly.range <- data.frame(matrix(as.numeric(monthly.max)-as.numeric(monthly.min), ncol = ncol(monthly.max)), row.names = index(monthly.max))
overall.monthly.range <- apply(monthly.range,2,mean)
days.27to29 <- data.frame(apply.yearly(xc,apply,2,function(x) sum(27 < x & x < 29)))
overall.days.27to29 <- apply(days.27to29,2,mean)
days.above28 <- data.frame(apply.yearly(xc,apply,2,function(x) sum(x > 28)))
overall.days.above28 <- apply(days.above28,2,mean)
colnames(weekly.range) <- colnames(annual.weekly.range) <- colnames(monthly.range) <- colnames(weekly.max)
rownames(annual.weekly.range) <- rownames(days.27to29) <- rownames(days.above28) <- substr(rownames(annual.weekly.range),1,4)

annual.mean <- data.frame(apply.yearly(xc,mean))
annual.max <- data.frame(apply.yearly(xc,apply,2,max))
annual.min <- data.frame(apply.yearly(xc,apply,2,min))
annual.range <- data.frame(matrix(as.numeric(apply.yearly(xc,apply,2,max))-as.numeric(apply.yearly(xc,apply,2,min)), ncol = ncol(annual.max)), row.names = substr(rownames(annual.max),1,4))
overall.mean <- apply(xc,2,mean)
overall.max <- apply(xc,2,max)
overall.min <- apply(xc,2,min)
overall.annual.range <- apply(annual.range,2,mean)
summer.mean <- data.frame(apply.yearly(xc[.indexmon(xc) %in% c(6,7,8)], mean))
overall.summer.mean <- apply(summer.mean,2,mean)
colnames(annual.range) <- colnames(annual.max)
rownames(annual.mean) <- rownames(annual.max) <- rownames(annual.min) <- rownames(summer.mean) <- substr(rownames(annual.mean),1,4)

save(xc,overall.weekly.range,monthly.mean,overall.monthly.range,overall.days.27to29,overall.days.above28,overall.mean,overall.min,overall.max,overall.annual.range,overall.summer.mean,file=paste0('tempSumm_',args[1],'.Rdata'))
